import type { BuiltinAgentDefinition, BuiltinFlowDefinition, CustomAgent, CustomFlow, WorkflowCatalog } from "@/core/workflow-catalog";

export const customAgent: CustomAgent = { id: "a".repeat(32), name: "Analista próprio", description: "Investiga com evidências", instructions: "Leia os arquivos e apresente evidências.", usage: "mixed", capability: "read_only", model: null };
export const customFlow: CustomFlow = { id: "b".repeat(32), name: "Meu fluxo", description: "Análise personalizada", entry: "c".repeat(32), maxSteps: 12, steps: [{ id: "c".repeat(32), agentId: customAgent.id, instructions: "", position: { x: 40, y: 40 }, next: null, onRework: null }] };
export const builtinAgent: BuiltinAgentDefinition = { id: "builtin:designer", name: "Designer", description: "Implementa interfaces.", instructions: "Implemente o escopo visual.", role: "designer", usage: "flow_only", capability: "commands", appearance: { icon: "palette", color: "purple" }, immutable: true };
export const builtinGithubAgent: BuiltinAgentDefinition = { id: "builtin:github", name: "GitHub", description: "Gerencia Git e GitHub com aprovação.", instructions: "Inspecione o repositório e proponha ações supervisionadas.", role: "github", usage: "mixed", capability: "commands", appearance: { icon: "rocket", color: "green" }, immutable: true };
export const builtinVideoAgent: BuiltinAgentDefinition = { id: "builtin:video", name: "Gerador de vídeos", description: "Gera apresentações de projetos com animação, narração e música e entrega o vídeo em MP4.", instructions: "Consulte video_docs e renderize a composição.", role: "video", usage: "mixed", capability: "commands", appearance: { icon: "film", color: "cyan" }, immutable: true };
export const builtinImageAgent: BuiltinAgentDefinition = { id: "builtin:image_generator", name: "Gerador de imagens", description: "Gera imagens e variações com o provedor configurado e prepara assets no ComfyUI.", instructions: "Gere imagens com o provedor configurado e prepare os assets usando image_process.", role: "image_generator", usage: "mixed", capability: "commands", appearance: { icon: "sparkles", color: "green" }, immutable: true };
export const builtinFlow: BuiltinFlowDefinition = { id: "designer", name: "Designer", description: "Implementação especializada em design e frontend.", entry: "builtin:designer:designer", maxSteps: 48, steps: [{ id: "builtin:designer:designer", agentId: builtinAgent.id, instructions: "", position: { x: 80, y: 120 }, next: null, onRework: null }], connections: [], appearance: { icon: "palette", color: "purple" }, immutable: true };
export const customCatalog: WorkflowCatalog = { revision: 2, agents: [customAgent], flows: [customFlow], builtinAgents: [builtinAgent, builtinGithubAgent], builtinFlows: [builtinFlow] };
