import { act, renderHook, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { idleVoice, voiceSession, voiceSettings, voiceTarget } from "@/test/voice-fixtures";
vi.mock("@tauri-apps/api/core", () => ({ invoke: vi.fn() }));
vi.mock("@tauri-apps/api/event", () => ({ listen: vi.fn() }));
afterEach(() => vi.restoreAllMocks());
describe("shared native voice state", () => {
  it("blocks microphone activation when subscriptions fail and retries without restarting", async () => {
    vi.resetModules();
    let failed = true;
    const stopped = vi.fn();
    vi.mocked(listen).mockImplementation(async name => {
      if (name === "voice:state" && failed) throw new Error("Listener unavailable");
      return stopped;
    });
    vi.mocked(invoke).mockReset().mockImplementation(async command => command === "get_voice_settings" ? voiceSettings() : command === "start_voice_session" ? voiceSession() : undefined);
    const { useVoice } = await import("./use-voice");
    const { result, unmount } = renderHook(useVoice);
    await waitFor(() => expect(result.current.error).toContain("Não foi possível acompanhar"));
    expect(result.current.settings).not.toBeNull();
    await act(async () => { await expect(result.current.start(voiceTarget, "dictation")).rejects.toContain("Tente novamente"); });
    expect(invoke).not.toHaveBeenCalledWith("start_voice_session", expect.anything());
    expect(stopped).toHaveBeenCalledTimes(4);
    failed = false;
    await act(async () => { await result.current.start(voiceTarget, "dictation"); });
    expect(invoke).toHaveBeenCalledWith("start_voice_session", { target: voiceTarget, mode: "dictation" });
    expect(result.current.active).toBe(true);
    expect(result.current.error).toBeNull();
    unmount();
    await waitFor(() => expect(stopped).toHaveBeenCalledTimes(7));
  });
  it("cleans up delayed subscriptions from an unmounted consumer without stopping its replacement", async () => {
    vi.resetModules();
    const pending: Array<(stop: () => void) => void> = [];
    const stopped = vi.fn(), replacementStopped = vi.fn();
    vi.mocked(listen).mockImplementation(() => new Promise(resolve => { pending.push(resolve); }));
    vi.mocked(invoke).mockReset().mockImplementation(async command => command === "get_voice_settings" ? voiceSettings() : command === "start_voice_session" ? voiceSession() : undefined);
    const { useVoice } = await import("./use-voice");
    const first = renderHook(useVoice);
    first.unmount();
    vi.mocked(listen).mockImplementation(async () => replacementStopped);
    const replacement = renderHook(useVoice);
    await waitFor(() => expect(replacement.result.current.settings).not.toBeNull());
    await act(async () => { pending.forEach(resolve => resolve(stopped)); });
    expect(stopped).toHaveBeenCalledTimes(3);
    expect(replacementStopped).not.toHaveBeenCalled();
    expect(replacement.result.current.error).toBeNull();
    await act(async () => { await replacement.result.current.start(voiceTarget, "dictation"); });
    expect(invoke).toHaveBeenCalledWith("start_voice_session", { target: voiceTarget, mode: "dictation" });
    replacement.unmount();
    await waitFor(() => expect(replacementStopped).toHaveBeenCalledTimes(3));
  });
  it("shares subscriptions, rejects old revisions and ignores malformed audio events", async () => {
    vi.resetModules();
    const events = new Map<string, (payload: unknown) => void>(), stopped = vi.fn();
    vi.mocked(listen).mockImplementation(async (name, callback) => { events.set(String(name), payload => callback({ event: String(name), id: 1, payload })); return stopped; });
    let complete: (value: unknown) => void = () => {};
    vi.mocked(invoke).mockImplementation(async command => command === "get_voice_settings" ? new Promise(resolve => { complete = resolve; }) : undefined);
    const { useVoice } = await import("./use-voice");
    const first = renderHook(useVoice), second = renderHook(useVoice);
    await waitFor(() => expect(events.size).toBe(3));
    await act(async () => { events.get("voice:state")?.(voiceSession({ revision: 9 })); complete(voiceSettings({ session: { ...idleVoice, revision: 1 } })); });
    expect(first.result.current.session?.revision).toBe(9); expect(second.result.current.active).toBe(true);
    await act(async () => { events.get("voice:state")?.({ id: "invalid" }); events.get("voice:state")?.(voiceSession({ revision: 8, phase: "idle" })); });
    expect(first.result.current.session?.phase).toBe("listening");
    first.unmount(); expect(stopped).not.toHaveBeenCalled(); second.unmount();
    await waitFor(() => expect(stopped).toHaveBeenCalledTimes(3));
  });
  it("starts recorded announcements with the optional clip and keeps controls limited to capture lifecycle", async () => {
    vi.resetModules(); vi.mocked(listen).mockImplementation(async () => () => {});
    vi.mocked(invoke).mockReset().mockImplementation(async command => command === "get_voice_settings" ? voiceSettings() : command === "start_voice_session" ? voiceSession({ mode: "announcement" }) : undefined);
    const { useVoice } = await import("./use-voice"); const { result, unmount } = renderHook(useVoice);
    await waitFor(() => expect(result.current.settings).not.toBeNull());
    await act(async () => { await result.current.start("companion-notice", "announcement", "Concluído.", "completed-1"); await result.current.control("voice-1", "end"); });
    expect(invoke).toHaveBeenCalledWith("start_voice_session", { target: "companion-notice", mode: "announcement", text: "Concluído.", clip: "completed-1" });
    expect(invoke).toHaveBeenCalledWith("control_voice_session", { sessionId: "voice-1", action: "end" });
    unmount();
  });
  it("stops only the submitted dictation and rejects a late final transcript before native cancellation resolves", async () => {
    vi.resetModules(); vi.mocked(listen).mockImplementation(async () => () => {});
    let ended: () => void = () => {};
    vi.mocked(invoke).mockReset().mockImplementation(async command => command === "get_voice_settings" ? voiceSettings({ session: voiceSession({ mode: "dictation" }) }) : command === "control_voice_session" ? new Promise<void>(resolve => { ended = resolve; }) : undefined);
    const { useVoice, stopDictation, acceptsDictationTranscript } = await import("./use-voice");
    const { result, unmount } = renderHook(useVoice);
    await waitFor(() => expect(result.current.active).toBe(true));
    await stopDictation("chat:other");
    expect(invoke).not.toHaveBeenCalledWith("control_voice_session", expect.anything());
    const stopping = stopDictation(voiceTarget);
    expect(acceptsDictationTranscript("voice-1")).toBe(false);
    expect(acceptsDictationTranscript("new-session")).toBe(true);
    expect(invoke).toHaveBeenCalledWith("control_voice_session", { sessionId: "voice-1", action: "end" });
    await act(async () => { ended(); await stopping; });
    unmount();
  });
  it("does not end an announcement on message submission and permits dictation retry when cancellation fails", async () => {
    vi.resetModules();
    const events = new Map<string, (payload: unknown) => void>();
    vi.mocked(listen).mockImplementation(async (name, callback) => { events.set(String(name), payload => callback({ event: String(name), id: 1, payload })); return () => {}; });
    vi.mocked(invoke).mockReset().mockImplementation(async command => command === "get_voice_settings" ? voiceSettings({ session: voiceSession({ mode: "announcement" }) }) : Promise.reject("Captura indisponível"));
    const { useVoice, stopDictation, acceptsDictationTranscript } = await import("./use-voice");
    const { result, unmount } = renderHook(useVoice);
    await waitFor(() => expect(result.current.active).toBe(true));
    await stopDictation(voiceTarget);
    expect(invoke).not.toHaveBeenCalledWith("control_voice_session", expect.anything());
    await act(async () => { events.get("voice:state")?.(voiceSession({ mode: "dictation", revision: 3 })); });
    await expect(stopDictation(voiceTarget)).rejects.toBe("Captura indisponível");
    expect(acceptsDictationTranscript("voice-1")).toBe(true);
    unmount();
  });
});
