//! Versioned IPC contracts shared by the Rust harness and the renderer.

/// Increment this value when a serialized IPC contract changes incompatibly.
pub(crate) const VERSION: u32 = 2;

/// Stable facade for the snapshot types serialized by Tauri commands.
pub(super) mod chat {
    pub(in crate::agent) use super::super::{ChatSnapshot, Step, ToolCall, Turn, Usage};
}

#[cfg(test)]
mod tests {
    use super::VERSION;
    use crate::agent::{
        attachments::Attachment,
        compaction::{CompactionEvent, ContextInfo},
        diffs::FileSummary,
        events::{ChatSubscription, Event, EventBatch, SnapshotState, StartedItem},
        history::{Excerpt, Window},
        provider::retry::Status as RetryStatus,
        queue::QueuedMessage,
        skill_input::MessagePart,
        tasks::{Status as TaskStatus, Task},
        workflow::Flow,
        AgentError, ApprovalDecision, ApprovalGrantDuration, ApprovalGrantRequest,
        ApprovalGrantScope, ApprovalMode, ApprovalPolicyDetails, ChatSnapshot, ContextReduction,
        Mode, PendingApproval, Step, ToolCall, Turn, TurnOptions, TurnStatus, Usage,
    };
    use crate::agent::{
        execution_grants::{ExecutionGrantSummary, GrantDurationKind, GrantMatch, GrantScopeKind},
        execution_policy::{CommandInvocation, CommandPlan, ExecutionEffects, Redirection},
        execution_sandbox::{SandboxAvailability, SandboxBackend, SandboxNetwork, SandboxReport},
    };
    use std::{fs, path::PathBuf};
    use ts_rs::TS;

    const CONTRACT_NAMES: &[&str] = &[
        "AgentError",
        "Mode",
        "ApprovalMode",
        "ExecutionEffects",
        "CommandInvocation",
        "Redirection",
        "CommandPlan",
        "SandboxBackend",
        "SandboxAvailability",
        "SandboxNetwork",
        "SandboxReport",
        "GrantMatch",
        "GrantScopeKind",
        "GrantDurationKind",
        "ExecutionGrantSummary",
        "ApprovalPolicyDetails",
        "PendingApproval",
        "ApprovalGrantScope",
        "ApprovalGrantDuration",
        "ApprovalGrantRequest",
        "ApprovalDecision",
        "Flow",
        "Attachment",
        "MessagePart",
        "TurnOptions",
        "TaskStatus",
        "DirectTask",
        "AgentTool",
        "RetryStatus",
        "Usage",
        "ContextReduction",
        "AgentStep",
        "TurnStatus",
        "AgentTurn",
        "QueuedMessage",
        "HistoryWindow",
        "HistoryExcerpt",
        "ContextInfo",
        "CompactionEvent",
        "FileChange",
        "ChatSnapshot",
        "StartedItem",
        "SnapshotState",
        "AgentEvent",
        "AgentEventBatch",
        "ChatSubscription",
    ];

    fn declarations() -> Vec<String> {
        vec![
            AgentError::decl(),
            Mode::decl(),
            ApprovalMode::decl(),
            ExecutionEffects::decl(),
            CommandInvocation::decl(),
            Redirection::decl(),
            CommandPlan::decl(),
            SandboxBackend::decl(),
            SandboxAvailability::decl(),
            SandboxNetwork::decl(),
            SandboxReport::decl(),
            GrantMatch::decl(),
            GrantScopeKind::decl(),
            GrantDurationKind::decl(),
            ExecutionGrantSummary::decl(),
            ApprovalPolicyDetails::decl(),
            PendingApproval::decl(),
            ApprovalGrantScope::decl(),
            ApprovalGrantDuration::decl(),
            ApprovalGrantRequest::decl(),
            ApprovalDecision::decl(),
            Flow::decl(),
            Attachment::decl(),
            MessagePart::decl(),
            TurnOptions::decl(),
            TaskStatus::decl(),
            Task::decl(),
            ToolCall::decl(),
            RetryStatus::decl(),
            Usage::decl(),
            ContextReduction::decl(),
            Step::decl(),
            TurnStatus::decl(),
            Turn::decl(),
            QueuedMessage::decl(),
            Window::decl(),
            Excerpt::decl(),
            ContextInfo::decl(),
            CompactionEvent::decl(),
            FileSummary::decl(),
            ChatSnapshot::decl(),
            StartedItem::decl(),
            SnapshotState::decl(),
            Event::decl(),
            EventBatch::decl(),
            ChatSubscription::decl(),
        ]
    }

    fn typescript() -> String {
        let mut output =
            String::from("// @generated by `bun run ipc:generate`; do not edit by hand.\n\n");
        output.push_str(&format!(
            "export const IPC_PROTOCOL_VERSION = {VERSION} as const;\n\n"
        ));
        output.push_str(
            "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n",
        );
        output.push_str(
            &declarations()
                .into_iter()
                .map(|declaration| format!("export {declaration}"))
                .collect::<Vec<_>>()
                .join("\n\n"),
        );
        output.push('\n');
        output
    }

    fn metadata() -> String {
        let contracts = CONTRACT_NAMES
            .iter()
            .map(|name| format!("    \"{name}\""))
            .collect::<Vec<_>>()
            .join(",\n");
        format!(
            "{{\n  \"protocolVersion\": {VERSION},\n  \"generator\": \"ts-rs@11\",\n  \"contracts\": [\n{contracts}\n  ]\n}}\n"
        )
    }

    fn generated_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/generated")
    }

    fn normalize_line_endings(content: &str) -> String {
        content.replace("\r\n", "\n")
    }

    #[test]
    fn generated_contract_comparison_accepts_windows_line_endings() {
        assert_eq!(
            normalize_line_endings("first\r\nsecond\r\n"),
            "first\nsecond\n"
        );
    }

    #[test]
    #[ignore = "writes versioned renderer contracts"]
    fn export_typescript_contracts() {
        let directory = generated_dir();
        fs::create_dir_all(&directory).expect("create generated contract directory");
        fs::write(directory.join("ipc.ts"), typescript()).expect("write TypeScript contracts");
        fs::write(directory.join("ipc.meta.json"), metadata()).expect("write contract metadata");
    }

    #[test]
    fn generated_contracts_are_current() {
        let directory = generated_dir();
        let expected_typescript = typescript();
        let actual_typescript =
            fs::read_to_string(directory.join("ipc.ts")).expect("read generated TypeScript");
        assert_eq!(
            normalize_line_endings(&actual_typescript),
            normalize_line_endings(&expected_typescript),
            "Rust IPC contracts changed; run `bun run ipc:generate`"
        );
        let expected_metadata = metadata();
        let actual_metadata =
            fs::read_to_string(directory.join("ipc.meta.json")).expect("read generated metadata");
        assert_eq!(
            normalize_line_endings(&actual_metadata),
            normalize_line_endings(&expected_metadata),
            "IPC compatibility metadata changed; run `bun run ipc:generate`"
        );
    }
}
